FROM acrowell/limbr:latest
MAINTAINER Alec Crowell <alexander.m.crowell@gmail.com>

#make actual data files
RUN make -f make_actual
RUN python3 src/knn_impute.py -i data/Formatted_input.txt -o output/actual/imputed_peptide.txt -m 0.3 -p 2
RUN python3 src/separate.py
RUN python3 src/sva_normalize.py -i output/actual/wt_for_sva.txt -o output/actual/wt_lowess_normed.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p -j output/actual/wt_pool_design.p
RUN python3 src/sva_normalize.py -i output/actual/csp_for_sva.txt -o output/actual/csp_lowess_normed.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p -j output/actual/csp_pool_design.p
RUN python3 src/sva_normalize.py -i output/actual/rna_for_sva.txt -o output/actual/rna_lowess_normed.txt -s 25 -n 12 -p 1000 -a .05 -d c -e r
RUN python3 src/old_normalize.py -i output/actual/wt_for_sva.txt -o output/actual/wt_old_normed.txt -e p -j output/actual/wt_pool_design.p
RUN python3 src/old_normalize.py -i output/actual/csp_for_sva.txt -o output/actual/csp_old_normed.txt -e p -j output/actual/csp_pool_design.p
RUN python3 src/old_normalize.py -i output/actual/rna_for_sva.txt -o output/actual/rna_old_normed.txt -e r
RUN sed -e 's/_[[:digit:]]//g' output/actual/wt_lowess_normed.txt > temp.txt
RUN cut -f 1,5- temp.txt > output/actual/wt_lowess_normed.txt
RUN python src/eJTK-CalcP.py -f output/actual/wt_lowess_normed.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN sed -e 's/_[[:digit:]]//g' output/actual/csp_lowess_normed.txt > temp.txt
RUN cut -f 1,5- temp.txt > output/actual/csp_lowess_normed.txt
RUN python src/eJTK-CalcP.py -f output/actual/csp_lowess_normed.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN sed -e 's/_[[:digit:]]//g' output/actual/rna_lowess_normed.txt > temp.txt
RUN mv temp.txt output/actual/rna_lowess_normed.txt
RUN python src/eJTK-CalcP.py -f output/actual/rna_lowess_normed.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN sed -e 's/_[[:digit:]]//g' output/actual/wt_old_normed.txt > temp.txt
RUN cut -f 1,5- temp.txt > output/actual/wt_old_normed.txt
RUN python src/eJTK-CalcP.py -f output/actual/wt_old_normed.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN sed -e 's/_[[:digit:]]//g' output/actual/csp_old_normed.txt > temp.txt
RUN cut -f 1,5- temp.txt > output/actual/csp_old_normed.txt
RUN python src/eJTK-CalcP.py -f output/actual/csp_old_normed.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN sed -e 's/_[[:digit:]]//g' output/actual/rna_old_normed.txt > temp.txt
RUN mv temp.txt output/actual/rna_old_normed.txt
RUN python src/eJTK-CalcP.py -f output/actual/rna_old_normed.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN rm output/actual/*__jtknull1000.txt
RUN rm output/actual/*__jtkout.txt 
