FROM acrowell/limbr:latest
MAINTAINER Alec Crowell <alexander.m.crowell.gr@dartmouth.edu>

RUN echo Generating Simulated Data
RUN python3 src/generate_simulated_data_mb.py

RUN echo Running eJTK
RUN for i in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do sed -e 's/_[[:digit:]]//g' output/simdata/mb_simulated_data_baseline_$i.txt > temp_baseline_$i.txt; done
RUN for i in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do mv temp_baseline_$i.txt output/simdata/mb_simulated_data_baseline_$i.txt; done
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_1.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_2.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_3.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_4.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_5.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_6.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_7.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_8.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_9.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_10.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_11.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_12.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_13.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_14.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_15.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_16.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_17.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_18.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_19.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_baseline_20.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt

RUN for i in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do sed -e 's/_[[:digit:]]//g' output/simdata/mb_simulated_data_with_noise_$i.txt > temp_with_noise_$i.txt; done
RUN for i in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do mv temp_with_noise_$i.txt output/simdata/mb_simulated_data_with_noise_$i.txt; done
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_1.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_2.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_3.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_4.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_5.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_6.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_7.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_8.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_9.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_10.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_11.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_12.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_13.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_14.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_15.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_16.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_17.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_18.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_19.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt
RUN python src/eJTK-CalcP.py -f output/simdata/mb_simulated_data_with_noise_20.txt -w src/ref_files/waveform_cosine.txt -a src/ref_files/asymmetries_02-22_by2.txt -s src/ref_files/phases_00-22_by2.txt -p src/ref_files/period24.txt

RUN echo Circadian Lowess SVA Normalizing
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_1.txt -o output/simdata/mb_denoised_circ_lowess_1.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_2.txt -o output/simdata/mb_denoised_circ_lowess_2.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_3.txt -o output/simdata/mb_denoised_circ_lowess_3.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_4.txt -o output/simdata/mb_denoised_circ_lowess_4.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_5.txt -o output/simdata/mb_denoised_circ_lowess_5.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_6.txt -o output/simdata/mb_denoised_circ_lowess_6.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_7.txt -o output/simdata/mb_denoised_circ_lowess_7.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_8.txt -o output/simdata/mb_denoised_circ_lowess_8.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_9.txt -o output/simdata/mb_denoised_circ_lowess_9.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_10.txt -o output/simdata/mb_denoised_circ_lowess_10.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_11.txt -o output/simdata/mb_denoised_circ_lowess_11.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_12.txt -o output/simdata/mb_denoised_circ_lowess_12.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_13.txt -o output/simdata/mb_denoised_circ_lowess_13.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_14.txt -o output/simdata/mb_denoised_circ_lowess_14.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_15.txt -o output/simdata/mb_denoised_circ_lowess_15.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_16.txt -o output/simdata/mb_denoised_circ_lowess_16.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_17.txt -o output/simdata/mb_denoised_circ_lowess_17.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_18.txt -o output/simdata/mb_denoised_circ_lowess_18.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_19.txt -o output/simdata/mb_denoised_circ_lowess_19.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_20.txt -o output/simdata/mb_denoised_circ_lowess_20.txt -s 25 -n 12 -p 1000 -a .05 -d c -e p

RUN echo Circadian Lowess SSE Normalizing
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_1.txt -o output/simdata/mb_denoised_circ_lowess_sse_1.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_2.txt -o output/simdata/mb_denoised_circ_lowess_sse_2.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_3.txt -o output/simdata/mb_denoised_circ_lowess_sse_3.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_4.txt -o output/simdata/mb_denoised_circ_lowess_sse_4.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_5.txt -o output/simdata/mb_denoised_circ_lowess_sse_5.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_6.txt -o output/simdata/mb_denoised_circ_lowess_sse_6.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_7.txt -o output/simdata/mb_denoised_circ_lowess_sse_7.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_8.txt -o output/simdata/mb_denoised_circ_lowess_sse_8.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_9.txt -o output/simdata/mb_denoised_circ_lowess_sse_9.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_10.txt -o output/simdata/mb_denoised_circ_lowess_sse_10.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_11.txt -o output/simdata/mb_denoised_circ_lowess_sse_11.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_12.txt -o output/simdata/mb_denoised_circ_lowess_sse_12.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_13.txt -o output/simdata/mb_denoised_circ_lowess_sse_13.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_14.txt -o output/simdata/mb_denoised_circ_lowess_sse_14.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_15.txt -o output/simdata/mb_denoised_circ_lowess_sse_15.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_16.txt -o output/simdata/mb_denoised_circ_lowess_sse_16.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_17.txt -o output/simdata/mb_denoised_circ_lowess_sse_17.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_18.txt -o output/simdata/mb_denoised_circ_lowess_sse_18.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_19.txt -o output/simdata/mb_denoised_circ_lowess_sse_19.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_20.txt -o output/simdata/mb_denoised_circ_lowess_sse_20.txt -s 25 -n 12 -p 1000 -a .05 -d l -e p

RUN echo Circadian Block SVA Normalizing
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_1.txt -o output/simdata/mb_denoised_block_1.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_2.txt -o output/simdata/mb_denoised_block_2.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_3.txt -o output/simdata/mb_denoised_block_3.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_4.txt -o output/simdata/mb_denoised_block_4.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_5.txt -o output/simdata/mb_denoised_block_5.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_6.txt -o output/simdata/mb_denoised_block_6.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_7.txt -o output/simdata/mb_denoised_block_7.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_8.txt -o output/simdata/mb_denoised_block_8.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_9.txt -o output/simdata/mb_denoised_block_9.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_10.txt -o output/simdata/mb_denoised_block_10.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_11.txt -o output/simdata/mb_denoised_block_11.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_12.txt -o output/simdata/mb_denoised_block_12.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_13.txt -o output/simdata/mb_denoised_block_13.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_14.txt -o output/simdata/mb_denoised_block_14.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_15.txt -o output/simdata/mb_denoised_block_15.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_16.txt -o output/simdata/mb_denoised_block_16.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_17.txt -o output/simdata/mb_denoised_block_17.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_18.txt -o output/simdata/mb_denoised_block_18.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_19.txt -o output/simdata/mb_denoised_block_19.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
RUN python3 src/sva_normalize.py -i output/simdata/mb_simulated_data_with_noise_for_sva_20.txt -o output/simdata/mb_denoised_block_20.txt -s 25 -n 12 -p 1000 -a .05 -d b -b data/block_design.p -e p
