FROM ubuntu:latest
MAINTAINER Alec Crowell <alexander.m.crowell.gr@dartmouth.edu>

# Install all the software needed to run the pipeline
RUN export LANG=C.UTF-8
RUN apt-get -qq update
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
RUN apt-get -y build-dep r-base
RUN apt-get -y install software-properties-common curl
RUN mkdir /usr/local/src/R
WORKDIR /usr/local/src/R
RUN curl -O http://cran.utstat.utoronto.ca/src/base/R-3/R-3.4.1.tar.gz
RUN tar xzvf R-3.4.1.tar.gz
WORKDIR R-3.4.1
RUN ./configure --enable-R-shlib  --with-blas --with-lapack
RUN make
RUN make install
WORKDIR /usr/local/src/R
RUN rm -f R Rscript
RUN ln -s R-3.4.1/bin/R R
RUN ln -s R-3.4.1/bin/Rscript Rscript
WORKDIR /
RUN add-apt-repository 'deb [arch=amd64,i386] http://cran.rstudio.com/bin/linux/ubuntu precise/'
RUN apt-get install -y wget git python python3 nano python-tk python3-pip python-pip python3-tk texlive
RUN su - -c "R -e \"install.packages('circular', repos = 'http://cran.rstudio.com/')\""
RUN add-apt-repository ppa:git-core/ppa
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs
RUN git lfs install
RUN pip2 install --upgrade pip
RUN pip3 install --upgrade pip
RUN pip3 install -U pandas scipy sklearn numpy statsmodels cython matplotlib tqdm multiprocess seaborn astroML rpy2 jinja2 LIMBR
RUN pip2 install -U numpy scipy cython matplotlib pandas statsmodels LIMBR
