FROM ubuntu:latest
MAINTAINER Alec Crowell <alexander.m.crowell.gr@dartmouth.edu>

# Install all the software needed to run the pipeline
RUN apt-get -qq update
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
RUN apt-get -y install software-properties-common curl
RUN add-apt-repository 'deb [arch=amd64,i386] http://cran.rstudio.com/bin/linux/ubuntu precise/'
RUN add-apt-repository 'deb https://<my.favorite.ubuntu.mirror>/ trusty-backports main restricted universe'
RUN apt-get install -y wget git python python3 nano python-tk python3-pip python-pip python3-tk r-base texlive-full
RUN su - -c "R -e \"install.packages('circular', repos = 'http://cran.rstudio.com/')\""
RUN add-apt-repository ppa:git-core/ppa
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs
RUN git lfs install
RUN pip2 install --upgrade pip
RUN pip3 install --upgrade pip
RUN pip3 install -U pandas scipy sklearn numpy statsmodels cython matplotlib tqdm multiprocess seaborn astroML
RUN pip2 install -U numpy scipy cython matplotlib pandas statsmodels

# clone the most recent version of the pipeline
RUN git lfs clone https://github.com/aleccrowell/LIMBR.git
RUN mkdir ./LIMBR/output/
RUN mkdir ./LIMBR/output/actual/
#RUN cp ./data/*.txt ./LIMBR/data/
RUN mkdir ./LIMBR/output/simdata/
RUN mkdir ./LIMBR/output/figs/
WORKDIR /LIMBR/src/bin/
RUN python3 setup.py build_ext --inplace
RUN python setup.py build_ext --inplace
WORKDIR /LIMBR/
