FROM acrowell/limbr:latest
MAINTAINER Alec Crowell <alexander.m.crowell.gr@dartmouth.edu>

RUN git lfs pull
RUN curl 'https://github.com/aleccrowell/LIMBR/releases/download/v0.1-alpha/Formatted_input.txt' -o data/Formatted_input.txt

#make actual data files
RUN make -f make_actual
