FROM acrowell/limbr:v12
MAINTAINER Alec Crowell <alexander.m.crowell.gr@dartmouth.edu>

#make actual data files
RUN git pull
RUN rm output/simdata/mb_ROC_curves_1.pdf
RUN rm output/simdata/mb_ROC_curves_2.pdf
RUN rm output/simdata/simdata_mb.csv
RUN make -f make_figs_mb
RUN make -f make_figs
