FROM acrowell/limbr:latest
MAINTAINER Alec Crowell <alexander.m.crowell.gr@dartmouth.edu>

RUN apt-get install software-properties-common
RUN add-apt-repository ppa:git-core/ppa
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs
RUN git lfs install
RUN git lfs pull
#RUN curl 'https://github.com/aleccrowell/LIMBR/releases/download/v0.1-alpha/Formatted_input.txt' -o data/Formatted_input.txt

#make actual data files
RUN make -f make_actual
